### PR TITLE
Add french support

### PR DESCRIPTION
**Pull request by g-bougard**

### CODE REVIEW

**Comment by g-bougard** [comment]
This needs to be tested anyway and I'll only be able to on monday. There's no urgency.

**Comment by redddcyclone** [comment]
Hi @g-bougard 

Thanks for the contribution! 

I tested it in my PC, most of it is good but the "Voir le journal de l'agent" string doesn't fit the button in the main window (in the right click menu it is OK). Is it possible to trim it down? If not, maybe I can try to resize the button.

The same thing happened in the italian translation and I had to ask the author to trim down the string too 😅

See:
image

**Comment by g-bougard** [comment]
No problem, this should be fine now.

**Comment by g-bougard** [comment]
I'll ask colleagues to provide other languages. At least spanish should be possible.

P.S.: But merge this PR if you're okay, I'll provide other PR with other languages when possible.

**Comment by redddcyclone** [comment]
Hi @g-bougard 

As per my tests, seems like everything is fine. The rest of the possible messages are message boxes and shouldn't have any problem with not fitting a window control. So I think I'll be already merging this PR.

Thanks a lot for the contribution!

**Pull request merged**
