### PR TITLE
Update GLPI-AgentMonitor.rc

### PR DESCRIPTION
**Pull request by kintaro1981**
added italian translation

I tried with visual studio 2022 but it gave me a problem during .exe creation, it was detected as a virus: Gen:Variant.Tedy.375120 from BitDefender.

Can you check if is all ok?

### CODE REVIEW

**Review by redddcyclone — CHANGES_REQUESTED** [review]
https://github.com/redddcyclone/glpi-agentmonitor/blob/90c36139817880c7860471498c4508875f76e719/GLPI-AgentMonitor.rc#L408

This string above is too big for the button. Is it possible to trim it down?

**Comment by redddcyclone** [comment]
Hi @kintaro1981

First of all, thanks for the contribution!

About BitDefender, it is a false positive. Please try compiling for x64 when testing, or if the same happens, put an exclusion in the antivirus. 

About the translation, mostly everything is good, but could you see if it's possible to make the change I requested above?
Thanks!

**Comment by kintaro1981** [comment]
> This string above is too big for the button. Is it possible to trim it down?

Yes
> About BitDefender, it is a false positive. Please try compiling for x64 when testing, or if the same happens, put an exclusion in the antivirus.
> 
> About the translation, mostly everything is good, but could you see if it's possible to make the change I requested above? Thanks!

I finally compiled it successfully. 
how I change the pull request with the GLPI-AgentMonitor.rc updated and fixed?
I need to do modify it in my repository and then do another pull request?

**Comment by kintaro1981** [comment]
Maybe I done it.
I changed the file in my repo and saved in the same branch (sorry but I'm a newbie of git)

**Comment by redddcyclone** [comment]
Just commit the updated file. Every commit you do to the branch you want to
merge in my repository will be automatically referenced.

**Review by redddcyclone — APPROVED** [review]
Okay, now the string fits inside the button. Thank you!

**Pull request merged**
