### PR TITLE
Added Catalan translations

### PR DESCRIPTION
**Pull request by bertugarangou**
Hello!

I added the translation to Catalan.

If there is any error or anything I need to modify or I did wrong, please let me know to solve it.

Thanks!

### CODE REVIEW

**Comment by redddcyclone** [comment]
Hi @bertugarangou 

First of all, thanks for the contribution!

Did you edit the resource file by hand? The sublanguage ID ```SUBLANG_CATALAN_CA``` is not recognized and the code won't compile. I tried adding a Catalan string table on Visual Studio and the correct header should be like this:
```
// Català (Català) resources

#if !defined(AFX_RESOURCE_DLL) || defined(AFX_TARG_CAT)
LANGUAGE LANG_CATALAN, SUBLANG_DEFAULT
```

Could you fix this?

**Comment by bertugarangou** [comment]
Hello,

I used VSCode, should I have used Visual Studio (visualstudio.microsoft.com), right?

**Comment by redddcyclone** [comment]
I don't know if VSCode supports editing resource files like Visual Studio does... it would be better if you used Visual Studio for this. But seeing as you already translated the string table, it would be sufficient if you just changed that part I mentioned above. I'll test the translation and if any other errors occur, then I'll ask you to create a new string table in Visual Studio.

**Comment by bertugarangou** [comment]
Let's try it, So sorry I am sure you are right. If it fails I will take a look to VS.

Thanks and sorry for the misunderstand

**Comment by redddcyclone** [comment]
No need to say sorry!

The code now compiled fine, but the string for the "View agent logs" button on the main window is too big. Could you trim it somehow?

image

**Comment by bertugarangou** [comment]
Of course, I wrote an alternative.

**Comment by redddcyclone** [comment]
Okay, everything is fine. Thanks a lot for the contribution, @bertugarangou!

**Pull request merged**
