### PR TITLE
Release 1.2.0

### PR DESCRIPTION
**Pull request by g-bougard**
Hi @redddcyclone 

I just released a 1.2.0.

Here are the changed for this release against your main branch.

### CODE REVIEW

**Comment by g-bougard** [comment]
Great, no false positive at that time on VirusTotal ! :tada:

**Comment by redddcyclone** [comment]
Hi @g-bougard 

That's great! I though the false positives for x86 would never end 😄 

Thanks for the release! I'll merge your changes and edit the readme to reflect the new version.

**Comment by redddcyclone** [comment]
@g-bougard 

I'm really sorry about it, but I just found another bug in the Monitor. This one is a bit specific: I wasn't clearing the notification string after clicking the "New ticket" button, and this causes the "Screenshot taken" notification to show everytime the systray icon changes color (when stopping or starting the service, for example). I commited the change to my repo. Can a revision release be provided?

**Comment by g-bougard** [comment]
Of course, don't worry.

**Pull request merged**
