### PR TITLE
Added Dutch translations to GLPI-AgentMonitor.rc

### PR DESCRIPTION
**Pull request by perplexityjeff**
Hi,

I've added a basic Dutch translation. I hope I've done it correctly :). 

Let me know!

Thank you,

Jeff

### CODE REVIEW

**Comment by redddcyclone** [comment]
Hi @perplexityjeff 

First of all, thanks for the contribution!

Didn't you miss some strings? Like "View agent logs", "Start service" and "Stop service"? Or were they intended to be left like this?

**Comment by perplexityjeff** [comment]
Hi @redddcyclone, 

I missed the "View agent logs" strings my bad, I made a commit to change it. "Start service" and "Stop service" works in Dutch as well as English (imo). 

Also I made some assumptions about this code:

`#if !defined(AFX_RESOURCE_DLL) || defined(AFX_TARG_NLD)
LANGUAGE LANG_DUTCH, SUBLANG_DUTCH`

I hope I did it correctly, if not let me know!

**Comment by perplexityjeff** [comment]
Changed capitilization from 'Agent' to 'agent'.

**Comment by redddcyclone** [comment]
Hi @perplexityjeff 

I tested it setting the locale to Dutch and it did work fine. Also, is "Service status" OK in english too?

**Comment by perplexityjeff** [comment]
Hi @redddcyclone,

Service status is fine in Dutch as well as in English :) (imo).

**Comment by redddcyclone** [comment]
@perplexityjeff 

OK, the translation has been merged. Thanks a lot for your contribution!

**Pull request merged**
