### PR TITLE
Set versioninfo variables from tag

### PR DESCRIPTION
**Pull request by g-bougard**
* Set version from tag when publishing
* Always to upload artifacts, even on failure
* Set internal filename to include arch to match released names

The tag must match the following pattern: MAJOR.MINOR.REV(-ANY_DESIRED_TAG)
- REV should be incremented when publishing a new build without change code?
- ANY_DESIRED_TAG should be used only to test the build or to publish beta.

### CODE REVIEW

**Comment by g-bougard** [comment]
This is a solution to answer glpi-project/glpi-agentmonitor#4

**Comment by redddcyclone** [comment]
Hi @g-bougard 

This is great, thank you!

But just one thing: should we really append the version to `PRODUCTNAME`? As it is already present on `PRODUCTVERSION`...

**Comment by g-bougard** [comment]
Tested again setting `1.0.1-build-test-3` as tag following your comment from the discussion: https://github.com/glpi-project/glpi-agentmonitor/actions/runs/4992716531
The only difference is my build includes the code signing step.
Everything seems okay, the draft release is also good.
There's still an issue with x86 version on VirusTotal, still a malicious false positive from DeepInstinct. This morning I tried to contact them to alert them of the problem. I really don't know if this can help as they don't have publicly communicated on how to report false positive cases.

**Comment by g-bougard** [comment]
> But just one thing: should we really append the version to `PRODUCTNAME`? As it is already present on `PRODUCTVERSION`...

The version is not added to PRODUCTNAME, only the part from the tag behind the first `-` char. For example, in my test, I set tag to `1.0.1-build-test-3`, so PRODUCTNAME is set to `GLPI Agent Monitor (build-test-3)`. For normal release there won't be anything added. This is just cosmetic but this is the best way I know to have a difference between a binary built by `1.0.1-build-test-3` tag & one built by `1.0.1-build-test-4` tag.
Here is the result for the file details in windows of my test:
image

**Comment by redddcyclone** [comment]
Ahh, I'm sorry, I didn't notice it was just the `-` part. I agree, this is a good way to separate the built binaries.

Thanks for the contribution, @g-bougard!

**Pull request merged**
